name: Android Build

concurrency:
  group: android_build_${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "console/**"
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "console/**"

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.5

    - name: Build the Artifact
      run: |
        cd android_v8
        gradle build --debug

    - name: Upload the Artifact
      uses: actions/upload-artifact@v4
      with:
        name: javet-shell-android-v8
        path: android_v8/app/build/outputs/apk/release/*.apk
