name: Console Build

concurrency:
  group: console_build_${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
      - "docs/**"
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build_jar:
    name: Build Jar
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2

    - name: Build the Artifact
      run: |
        cd console
        gradle build --debug

    - name: Upload the Artifact
      uses: actions/upload-artifact@v3
      with:
        name: javet-shell-console
        path: console/build/libs/*.jar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Build and Push
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/javet-shell:latest -f docker/console.Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/javet-shell:latest
